### ISSUE TITLE
Make interface consistent

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1086]
As discussed in #1085, we have different notions how a set should be represented. Keywords are using comma separated lists, while tools use arrays/lists of strings.

- [ ] clear decision on the best structure
- [ ] update the internal storage to support a unique data structure
- [ ] update API description to reflect the current and the updated version of the data structure

**Comment by christianlupus** [comment]
With #1087 this might be obsolete, depending on the decisions.
