### ISSUE TITLE
Updated parsing routines for recipes and output

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1110]
Currently, we are checking, filtering and consolidating all data during the import of recipes. This is done with the final output of the app in mind. With #191 and #306 we will have to parse again and transcribe to another format. If new features are supported (e.g. #206, #8 , or #323), we might need more information or in other formats that we filtered out in an earlier release.

We should instead keep the original JSON present as long as possible and save it in the future. Only basic parsing/validation is done in order to ensure syntactical correctness. Then, there should be a parser to transfer the recipes into an internal structure (of objects). These objects represent the complete data structure and allow easier validation and consolidation. Adding a Visitor pattern will allow to extract such objects in a very generic and efficient way.

- [ ] Write an intended architecture pattern (prose) on the steps for parsing/translating
- [ ] Create structural diagrams to support during implementation
- [ ] Define interfaces of involved class structures
- [ ] Implement basic data classes
- [ ] Create parser(s)
- [ ] Create output filter for current JSON output
- [ ] Create output filter for raw output
