### ISSUE TITLE
Enable support for prereleases and nightly releases

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1127]
According to https://help.nextcloud.com/t/creation-of-prereleases/142744 we could push out pre-releases to beta testers and also nightly releases.

- [ ] Make deploy scripts compatible with a release suffix (like `1.2.3-rc1`)
- [ ] Make deploy scripts capable of generating nightly releases
- [ ] Prepare a workflow for nightly release generation

**Comment by christianlupus** [comment]
Duplicate of #1132
