### ISSUE TITLE
Speed up CI testing

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1689]
The CI testing could be faster. Here, some ideas can be collected

- [ ] Separate migration tests from main tests and run the migration tests only three times (once per DB system)
- [ ] Install NC core only once and reuse it using artifacts/caches
- [ ] Use one PHP version for installation and do not install for each version
- [ ] Cache Docker container images
