### ISSUE TITLE
prepare split of versions

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1889]
The upcoming changes in the server makes the splitting of the code base necessary. Some fixes need to be addressed:

- [x] creation of second set of branches
- [x] registering with transifex
- [x] correcting the release scripts
